apiVersion: v1
kind: Service
metadata:
  name: redis-lb
  labels:
    app: redis
spec:
  type: LoadBalancer  # LoadBalancer를 사용하여 외부 접근 가능하도록 설정
#  clusterIP: None  # ✅ 반드시 None으로 설정 (Headless Service)
  ports:
    - port: 6379      # Redis 기본 포트
      targetPort: 6379
  selector:
    app: redis
