apiVersion: v1
kind: Service
metadata:
  name: redis-external
spec:
  type: NodePort  # 외부에서 접근 가능하도록 설정
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379  # 내부 Redis 포트
      targetPort: 6379
      nodePort: 30079  # ❗ 사용 가능한 NodePort 범위(30000-32767)
